const {
  AndroidConfig,
  withAndroidStyles,
  withDangerousMod,
  withMainApplication,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// 1. System bars: don't let Android paint a "contrast" scrim behind the
//    transparent status/navigation bars. On Samsung One UI that scrim showed up
//    as a second grey band under the chat composer, so the input bar looked
//    doubled. Needs API 29+, hence tools:targetApi.
// ---------------------------------------------------------------------------
function withoutSystemBarContrast(config) {
  return withAndroidStyles(config, (cfg) => {
    const { assignStylesValue, getAppThemeGroup } = AndroidConfig.Styles;
    for (const name of [
      "android:enforceStatusBarContrast",
      "android:enforceNavigationBarContrast",
    ]) {
      cfg.modResults = assignStylesValue(cfg.modResults, {
        add: true,
        parent: getAppThemeGroup(),
        name,
        value: "false",
        targetApi: "29",
      });
    }
    return cfg;
  });
}

// ---------------------------------------------------------------------------
// 2. AppRestart native module.
//    React Native only reads I18nManager's RTL flag when the native process
//    starts, so switching to an RTL language (Arabic/Farsi/Urdu/…) has no
//    visible effect until the app relaunches. expo-updates isn't installed and
//    DevSettings is dev-only, so release builds had no way to restart — the
//    strings changed but the layout never mirrored. This module does a real
//    process restart, callable from JS as NativeModules.AppRestart.restart().
// ---------------------------------------------------------------------------
const restartModuleKt = (pkg) => `package ${pkg}

import android.content.Intent
import android.os.Handler
import android.os.Looper
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * Fully restarts the app process from JS (NativeModules.AppRestart.restart()).
 *
 * Needed for right-to-left languages: React Native only reads the layout
 * direction (RTL) flag when the native process starts, so forceRTL(true) has no
 * visible effect until the app relaunches. We launch a fresh copy of the
 * launcher task WHILE the app is still in the foreground (so Android allows the
 * activity start — a launch scheduled after the process dies would be blocked as
 * a background start), then kill this process.
 *
 * Generated by plugins/withZappchatNative.js — edit it there, not here.
 */
class RestartModule(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  override fun getName() = "AppRestart"

  @ReactMethod
  fun restart() {
    val ctx = reactApplicationContext
    val launch =
      ctx.packageManager.getLaunchIntentForPackage(ctx.packageName) ?: return
    val component = launch.component ?: return
    val activity = ctx.currentActivity
    // Brief delay so any pending SharedPreferences writes (notably I18nManager's
    // RTL flag, written with apply()) flush before we exit — otherwise the app
    // could relaunch in the previous direction. The app is still foreground
    // during this delay, so the activity start below is permitted.
    Handler(Looper.getMainLooper()).postDelayed({
      val restartIntent = Intent.makeRestartActivityTask(component)
      (activity ?: ctx).startActivity(restartIntent)
      Runtime.getRuntime().exit(0)
    }, 150)
  }
}
`;

const restartPackageKt = (pkg) => `package ${pkg}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/** Generated by plugins/withZappchatNative.js — edit it there, not here. */
class RestartPackage : ReactPackage {
  override fun createNativeModules(
    reactContext: ReactApplicationContext
  ): List<NativeModule> = listOf(RestartModule(reactContext))

  override fun createViewManagers(
    reactContext: ReactApplicationContext
  ): List<ViewManager<*, *>> = emptyList()
}
`;

function withAppRestartModule(config) {
  // Write the two Kotlin sources into the app's package directory.
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const pkg = AndroidConfig.Package.getPackage(cfg);
      if (!pkg) {
        throw new Error(
          "withZappchatNative: expo.android.package is not set in app.json"
        );
      }
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "java",
        ...pkg.split(".")
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, "RestartModule.kt"),
        restartModuleKt(pkg),
        "utf8"
      );
      fs.writeFileSync(
        path.join(dir, "RestartPackage.kt"),
        restartPackageKt(pkg),
        "utf8"
      );
      return cfg;
    },
  ]);

  // Register the package in MainApplication's package list.
  config = withMainApplication(config, (cfg) => {
    const contents = cfg.modResults.contents;
    if (contents.includes("add(RestartPackage())")) return cfg;

    const anchor = /(PackageList\(this\)\.packages\.apply\s*\{)/;
    if (!anchor.test(contents)) {
      throw new Error(
        "withZappchatNative: could not find PackageList(this).packages.apply { in MainApplication — " +
          "the Expo template changed, update this plugin."
      );
    }
    cfg.modResults.contents = contents.replace(
      anchor,
      "$1\n          add(RestartPackage())"
    );
    return cfg;
  });

  return config;
}

/**
 * Keeps Zappchat's hand-written Android tweaks reproducible: `expo prebuild`
 * regenerates them, so a fresh clone builds without any manual native edits.
 */
module.exports = function withZappchatNative(config) {
  config = withoutSystemBarContrast(config);
  config = withAppRestartModule(config);
  return config;
};
