package __PACKAGE__

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.media.AudioAttributes
import android.media.AudioManager
import android.media.MediaPlayer
import android.media.RingtoneManager
import android.net.Uri
import android.os.Build
import android.provider.Settings
import androidx.core.app.NotificationCompat
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * WhatsApp-style incoming call: a full-screen, ringing notification that shows
 * over the lock screen.
 *
 * The full-screen intent launches MainActivity (which sets showWhenLocked /
 * turnScreenOn), so the app's own CallOverlay draws the Answer/Decline UI —
 * that keeps one call UI instead of a second native one.
 *
 * The ringtone is played here with a looping MediaPlayer rather than via the
 * channel's sound, because a channel sound plays once and we want it to keep
 * ringing until answered.
 *
 * Generated by plugins/withZappchatNative.js — edit it there, not here.
 */
class IncomingCallModule(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  private var player: MediaPlayer? = null

  override fun getName() = "IncomingCall"

  companion object {
    const val CHANNEL_ID = "calls"
    const val NOTIFICATION_ID = 42424
    const val EXTRA_CALL_ID = "incomingCallId"
  }

  private fun notificationManager(ctx: Context) =
    ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

  /** High-importance channel that can ring over Do Not Disturb. */
  private fun ensureChannel(ctx: Context) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
    val nm = notificationManager(ctx)
    if (nm.getNotificationChannel(CHANNEL_ID) != null) return
    val channel =
      NotificationChannel(CHANNEL_ID, "Calls", NotificationManager.IMPORTANCE_HIGH).apply {
        description = "Incoming calls"
        // No channel sound: we loop the ringtone ourselves so it rings until answered.
        setSound(null, null)
        enableVibration(true)
        vibrationPattern = longArrayOf(0, 1000, 1000)
        lockscreenVisibility = NotificationCompat.VISIBILITY_PUBLIC
        setBypassDnd(true)
      }
    nm.createNotificationChannel(channel)
  }

  @ReactMethod
  fun show(callId: String, fromName: String, media: String) {
    val ctx = reactApplicationContext
    ensureChannel(ctx)

    val launch =
      ctx.packageManager.getLaunchIntentForPackage(ctx.packageName)?.apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
        putExtra(EXTRA_CALL_ID, callId)
      }
    val pending =
      PendingIntent.getActivity(
        ctx,
        0,
        launch,
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
      )

    val text = if (media == "video") "Incoming video call" else "Incoming call"
    val notification =
      NotificationCompat.Builder(ctx, CHANNEL_ID)
        .setSmallIcon(ctx.applicationInfo.icon)
        .setContentTitle(if (fromName.isBlank()) "Incoming call" else fromName)
        .setContentText(text)
        .setPriority(NotificationCompat.PRIORITY_MAX)
        .setCategory(NotificationCompat.CATEGORY_CALL)
        .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
        .setOngoing(true)
        .setAutoCancel(false)
        // `true` = show the full screen UI even if the device is already awake.
        .setFullScreenIntent(pending, true)
        .setContentIntent(pending)
        .build()

    notificationManager(ctx).notify(NOTIFICATION_ID, notification)
    startRinging(ctx)
  }

  @ReactMethod
  fun dismiss() {
    val ctx = reactApplicationContext
    try {
      notificationManager(ctx).cancel(NOTIFICATION_ID)
    } catch (e: Exception) {
      /* ignore */
    }
    stopRinging()
  }

  /**
   * Android 14+ only auto-grants USE_FULL_SCREEN_INTENT to calling/alarm apps.
   * If it isn't granted the notification degrades to a heads-up banner (it still
   * rings), so the app can use this to offer the user a way to turn it on.
   */
  @ReactMethod
  fun canUseFullScreen(promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT < Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
        promise.resolve(true)
        return
      }
      promise.resolve(notificationManager(reactApplicationContext).canUseFullScreenIntent())
    } catch (e: Exception) {
      promise.resolve(true)
    }
  }

  /** Opens the system screen where the user can allow full-screen notifications. */
  @ReactMethod
  fun openFullScreenSettings() {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.UPSIDE_DOWN_CAKE) return
    try {
      val ctx = reactApplicationContext
      val intent =
        Intent(Settings.ACTION_MANAGE_APP_USE_FULL_SCREEN_INTENT).apply {
          data = Uri.parse("package:" + ctx.packageName)
          addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
      ctx.startActivity(intent)
    } catch (e: Exception) {
      /* ignore */
    }
  }

  private fun startRinging(ctx: Context) {
    stopRinging()
    try {
      // Respect the ringer: on silent/vibrate we let the channel's vibration
      // carry it rather than forcing sound out of a silenced phone.
      val am = ctx.getSystemService(Context.AUDIO_SERVICE) as AudioManager
      if (am.ringerMode != AudioManager.RINGER_MODE_NORMAL) return

      val uri: Uri =
        RingtoneManager.getActualDefaultRingtoneUri(ctx, RingtoneManager.TYPE_RINGTONE)
          ?: Settings.System.DEFAULT_RINGTONE_URI
          ?: return

      player =
        MediaPlayer().apply {
          setDataSource(ctx, uri)
          setAudioAttributes(
            AudioAttributes.Builder()
              .setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE)
              .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
              .build()
          )
          isLooping = true
          prepare()
          start()
        }
    } catch (e: Exception) {
      player = null
    }
  }

  private fun stopRinging() {
    try {
      player?.let {
        if (it.isPlaying) it.stop()
        it.release()
      }
    } catch (e: Exception) {
      /* ignore */
    }
    player = null
  }

  override fun onCatalystInstanceDestroy() {
    stopRinging()
  }
}
